version: 2.1


defaults: &defaults
  docker:
    - image: circleci/node:10


orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: npm run compile

  bench:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: npm run compile
      - run: node build/build.js
      - persist_to_workspace:
          root: .
          paths:
            - docs
            - dist
            - .git

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List Workspace
          command: ls
      - run:
          name: cd dist
          command: cd dist
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
#      - run:
#          name: Publish package
#          command: npm publish



  pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List Workspace
          command: ls
      - run:
          name: cd docs
          command: cd docs
      - run: git config --global user.email "ahmetcanguven44@gmail.com"
      - run: git config --global user.name "CirleCi"
      - run: git checkout gh-pages
      - run: git add .
      - run: git commit -m "update docs"
      - run: git push


workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - bench:
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - bench
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
      - pages:
          requires:
            - deploy
