version: 2.1


defaults: &defaults
  docker:
    - image: circleci/node:10

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - store_artifacts:
          path: coverage
      - run: npm run compile
      - codecov/upload:
          file: coverage/*.json

  bench:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: npm run compile
      - run: node build/build.js
      - persist_to_workspace:
          root: .
          paths:
            - docs
            - dist
            - README.md

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List Workspace
          command: ls
      - run:
          name: Authenticate with registry
          command: cd dist && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: cd dist && npm publish



  pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List Workspace
          command: ls
      - add_ssh_keys:
          fingerprints:
            - 7f:7c:9d:f0:a1:14:a3:7f:c6:6b:5c:22:b2:c6:0b:3b
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git config --global user.email "ahmetcanguven44@gmail.com"
      - run: git config --global user.name "CirleCi"
      - run: git clone git@github.com:Acanguven/rapidash.git
      - run: cd /home/circleci/project/rapidash && git checkout gh-pages
      - run: cd /home/circleci/project/rapidash && rm -r ./*
      - run: cd /home/circleci/project/rapidash && mv ../docs/* .
      - run: cd /home/circleci/project/rapidash && git add .
      - run: cd /home/circleci/project/rapidash && git commit -m "update docs"
      - run: cd /home/circleci/project/rapidash && git push


workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - bench:
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - bench
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
      - pages:
          requires:
            - deploy
